// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbGmoX7EKupyLdlYmLiMYft2-g5h4oVQg',
    appId: '1:92865095776:web:4882e3b237931eefe27b05',
    messagingSenderId: '92865095776',
    projectId: 'fir-test-39697',
    authDomain: 'fir-test-39697.firebaseapp.com',
    storageBucket: 'fir-test-39697.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf-pYiSDeFnCBHaT5w7dyvkjPqz6PTzVY',
    appId: '1:92865095776:android:0f0d112479635703e27b05',
    messagingSenderId: '92865095776',
    projectId: 'fir-test-39697',
    storageBucket: 'fir-test-39697.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAZ8JJ-Nap_t-tcIs8-407c8029AZ-uyU',
    appId: '1:92865095776:ios:0f5fa4211fe0274ce27b05',
    messagingSenderId: '92865095776',
    projectId: 'fir-test-39697',
    storageBucket: 'fir-test-39697.appspot.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAZ8JJ-Nap_t-tcIs8-407c8029AZ-uyU',
    appId: '1:92865095776:ios:0f5fa4211fe0274ce27b05',
    messagingSenderId: '92865095776',
    projectId: 'fir-test-39697',
    storageBucket: 'fir-test-39697.appspot.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbGmoX7EKupyLdlYmLiMYft2-g5h4oVQg',
    appId: '1:92865095776:web:20a74dfbdb7c3bd4e27b05',
    messagingSenderId: '92865095776',
    projectId: 'fir-test-39697',
    authDomain: 'fir-test-39697.firebaseapp.com',
    storageBucket: 'fir-test-39697.appspot.com',
  );
}
